on:
  push:
    branches:
      - v2
      - v2-dev
  pull_request:
    branches:
      - v2
      - v2-dev

name: Build

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add font-noto-cjk
            git config --global --add safe.directory /github/workspace
            cd sjtutex && l3build ctan
        name: build package with l3build
      - name: prepare upload artifacts
        run: |
          sudo rm -r sjtutex/build/distrib/tds/*/
          sudo unzip -d sjtutex/build/distrib/tds/ sjtutex/build/distrib/tds/sjtutex.tds.zip
          sudo rm sjtutex/build/distrib/tds/sjtutex.tds.zip
          sudo rm sjtutex/doc/sjtutex.pdf
      - uses: actions/upload-artifact@v3
        with:
          path: |
            sjtutex/build/distrib/tds/
          name: sjtutex.tds
        name: upload build tds artifacts
      - uses: actions/upload-artifact@v3
        with:
          path: |
            sjtutex/doc/
          name: samples
        name: upload build samples artifacts
