on:
  push:
    branches:
      - v2
      - v2-dev
  pull_request:
    branches:
      - v2
      - v2-dev

name: Build

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20240315
          run: |
            apk add zip diffutils font-noto-cjk
            git config --global --add safe.directory /home/runner/work/SJTUTeX/SJTUTeX
            cd sjtutex && l3build ctan
        name: build package with l3build
      - name: prepare upload artifacts
        run: |
          sudo rm sjtutex/build/distrib/tds/sjtutex.tds.zip
          sudo rm sjtutex/build/distrib/ctan/sjtutex-ctan.zip
          sudo rm sjtutex/build/distrib/ctan/sjtutex.tds.zip
      - uses: actions/upload-artifact@v4
        with:
          path: |
            sjtutex/build/distrib/ctan/
          name: sjtutex-ctan
        name: upload build ctan artifacts
      - uses: actions/upload-artifact@v4
        with:
          path: |
            sjtutex/build/distrib/tds/
          name: sjtutex.tds
        name: upload build tds artifacts
      - uses: actions/upload-artifact@v4
        with:
          path: |
            sjtutex/build/result
          name: samples
        name: upload build samples artifacts
