name: Build

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
  workflow_dispatch:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add zip diffutils font-noto-cjk
            git config --global --add safe.directory "${GITHUB_WORKSPACE}"
            cd sjtutex && l3build ctan && rm build/distrib/tds/sjtutex.tds.zip
      - name: Upload TDS
        uses: actions/upload-artifact@v4
        with:
          name: sjtutex.tds
          path: sjtutex/build/distrib/tds/
      - name: Upload samples
        uses: actions/upload-artifact@v4
        with:
          name: samples
          path: sjtutex/build/result/
