on:
  push:
    branches:
    - release
    tags:
    - "v*"

name: Release

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add zip diffutils font-noto-cjk
            git config --global --add safe.directory /home/runner/work/SJTUTeX/SJTUTeX
            cd sjtutex && l3build ctan
        name: build package
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          files: |
            sjtutex/sjtutex.pdf
            sjtutex/sjtutex-ctan.zip
            sjtutex/sjtutex.tds.zip
