on:
  push:
    branches:
    - release
    tags:
    - "v*"

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add zip diffutils font-noto-cjk
            git config --global --add safe.directory /home/runner/work/SJTUTeX/SJTUTeX
            cd sjtutex && l3build ctan
        name: build package
      - uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: true
      - name: add sjtutex.pdf
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sjtutex/sjtutex.pdf
          asset_name: sjtutex.pdf
          asset_content_type: application/pdf
      - name: add sjtutex-ctan.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sjtutex/sjtutex-ctan.zip
          asset_name: sjtutex-ctan.zip
          asset_content_type: application/x-zip
      - name: add sjtutex.tds.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sjtutex/sjtutex.tds.zip
          asset_name: sjtutex.tds.zip
          asset_content_type: application/x-zip