name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add zip diffutils font-noto-cjk
            git config --global --add safe.directory "${GITHUB_WORKSPACE}"
            cd sjtutex && l3build ctan
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ github.event.head_commit.message }}
          draft: true
          files: |
            sjtutex/sjtutex.pdf
            sjtutex/sjtutex-ctan.zip
            sjtutex/sjtutex.tds.zip
